language: go

go:
  - 1.7
  
install:
  - go get github.com/tcnksm/ghr
  
script: go build -ldflags="-s -w" -v -o hello && ls -alF && ./hello && ghr -t $secNval -u chikhpykh-org -r hello-go --replace v0.1.0 ./hello
