language: go

go:
  - 1.7
  
env:
  BUILD_PRM="-ldflags='-s -w' -v"
  
install:
  - go get github.com/tcnksm/ghr
  
script: go build $BUILD_PRM -o hello && ls -alF && ./hello && ghr -t $secNval -u chikhpykh-org -r hello-go --replace v0.1.0 ./hello
